server:
  port: 10006
spring:
  application:
    name: service-resume
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_resume
    username: root
    password: 3121
logging:
  level:
    com.com.groupseven.resume: debug
