spring:
  application:
    name: service-invite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_invite
    username: root
    password: 3121
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 10007

